# Daksh Kapoor
# Numpy
# Array

In [1]:
import numpy as np # importing numpy as an Alias
sim_lst=[3,4,5] #List of numbers
np.array(sim_lst) #conveet to array

array([3, 4, 5])

In [3]:
arr = np.array([6,7,8])
arr

array([6, 7, 8])

In [48]:
lst_O_lst = ([1,2,3],[4,5,6],[7,8,9])
np.array(lst_O_lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [7]:
np.arange(5,28,6)

array([ 5, 11, 17, 23])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(6, dtype = int)

array([0, 0, 0, 0, 0, 0])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

In [16]:
np.ones((2,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.linspace(10,20,15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(2,4) ### uniform distribution from 0 to 1

array([[0.06485563, 0.82446266, 0.76737847, 0.82144133],
       [0.18311327, 0.77855418, 0.70686461, 0.44464831]])

In [23]:
np.random.randn(2,4)

array([[ 1.05566579,  0.92267826,  0.57307405, -0.8787585 ],
       [-0.54716394, -0.58489954,  0.86593471, -1.37843284]])

In [26]:
np.random.randint(2,10,100)

array([8, 6, 4, 7, 8, 3, 9, 8, 2, 3, 9, 5, 4, 5, 2, 4, 5, 9, 4, 3, 6, 6,
       9, 6, 6, 8, 2, 9, 9, 9, 8, 9, 7, 8, 5, 9, 8, 3, 7, 8, 7, 8, 7, 5,
       5, 8, 8, 9, 3, 2, 8, 3, 8, 8, 2, 2, 5, 8, 3, 8, 4, 2, 9, 2, 8, 9,
       6, 7, 8, 7, 9, 3, 4, 5, 9, 9, 5, 3, 6, 5, 7, 4, 5, 3, 4, 5, 8, 8,
       8, 6, 5, 5, 9, 8, 5, 3, 2, 2, 3, 6])

In [27]:
np.random.randint(10,100,15)

array([84, 92, 27, 78, 19, 84, 37, 72, 53, 91, 48, 81, 52, 93, 85])

In [61]:
sam_arr=np.arange(2,20)
sam_arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [31]:
sam_arr=np.arange(2,20,4)
sam_arr

array([ 2,  6, 10, 14, 18])

In [32]:
sam_arr.min()

2

In [33]:
sam_arr.argmin()

0

In [42]:
sam_arr.argmax()

4

In [43]:
sam_arr.max()

18

In [50]:
sam_arr.dtype

dtype('int32')

In [58]:
sam_arr=np.arange(10,20)
sam_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
sam_arr[5]=100
sam_arr

array([  2,   3,   4,   5,   6, 100,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19])

In [63]:
sam_arr=np.arange(10,100)
sam_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [64]:
sam_arr[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [66]:
sam_arr[:]=1001
sam_arr

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

In [55]:
rand_arr=np.random.randint(0,10,5)
rand_arr

array([0, 0, 0, 0, 5])

In [36]:
rand_arr.min()

2

In [37]:
rand_arr.argmin()

2

In [40]:
rand_arr.max()

8

In [41]:
rand_arr.argmax()

4

In [44]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
rand_arr.dtype

dtype('int32')

In [69]:
sam_arr=sam_arr.reshape(3,8)

ValueError: cannot reshape array of size 90 into shape (3,8)

In [53]:
a=np.random.rand(2,3)
a

array([[0.19931062, 0.75098748, 0.20444407],
       [0.33965426, 0.68539624, 0.49531692]])

In [54]:
a.T

array([[0.19931062, 0.33965426],
       [0.75098748, 0.68539624],
       [0.20444407, 0.49531692]])